In [297]:
import pandas as pd
from datetime import datetime

# Hiển thị đủ số dòng và số cột mong muốn
pd.set_option("display.max_rows", 100)   # tối đa số dòng hiển thị
pd.set_option("display.max_columns", None)  # hiện tất cả các cột
pd.set_option("display.width", None)   # không giới hạn độ rộng

In [298]:
# Đường dẫn đầy đủ tới file Excel
excel_path = r"C:\Users\huuchinh.nguyen\Concentrix Corporation\WFM-Expedia-HCM - Branding files\Attendance\Expedia - ATD Report - 2025.10.xlsx"

# Đọc sheet Roster_Rawdata
df_roster = pd.read_excel(excel_path, sheet_name="Roster_Rawdata")

# Kiểm tra kích thước và xem trước dữ liệu
print("Kích thước sheet Roster_Rawdata:", df_roster.shape)
df_roster.head()

Kích thước sheet Roster_Rawdata: (155, 34)

,-,-.1,-.2,-.3,-.4,2025-09-29 00:00:00,2025-09-30 00:00:00,2025-10-01 00:00:00,2025-10-02 00:00:00,2025-10-03 00:00:00,2025-10-04 00:00:00,2025-10-05 00:00:00,2025-10-06 00:00:00,2025-10-07 00:00:00,2025-10-08 00:00:00,2025-10-09 00:00:00,2025-10-10 00:00:00,2025-10-11 00:00:00,2025-10-12 00:00:00,2025-10-13 00:00:00,2025-10-14 00:00:00,2025-10-15 00:00:00,2025-10-16 00:00:00,2025-10-17 00:00:00,2025-10-18 00:00:00,2025-10-19 00:00:00,2025-10-20 00:00:00,2025-10-21 00:00:00,2025-10-22 00:00:00,2025-10-23 00:00:00,2025-10-24 00:00:00,2025-10-25 00:00:00,2025-10-26 00:00:00,2025-10-27 00:00:00
0,IEX,Emp ID,Email,Agent Name,Wave,9/29/2025,9/30/2025,10/1/2025,10/2/2025,10/3/2025,10/4/2025,10/5/2025,10/6/2025,10/7/2025,10/8/2025,10/9/2025,10/10/2025,10/11/2025,10/12/2025,10/13/2025,10/14/2025,10/15/2025,10/16/2025,10/17/2025,10/18/2025,10/19/2025,10/20/2025,10/21/2025,10/22/2025,10/23/2025,10/24/2025,10/25/2025,10/26/2025,NaN
1,3085257,103082161,thikimchi.le@concentrix.com,LE THI KIM CHI,17,2100-0600,2100-0600,OFF,OFF,2000-0500,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,NaN
2,3090069,103116487,thanhhao.nguyen@concentrix.com,NGUYEN THANH HAO,24,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,1300-2200,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,CO,AL,OFF,OFF,2100-0600,2000-0500,2000-0500,2000-0500,2000-0500,OFF,OFF,2000-0500,NaN
3,3087504,103101215,hongphuc.nguyen3@concentrix.com,NGUYEN HONG PHUC,20,1300-2200,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,OFF,2100-0600-SHAL,2100-0600-SHAL,AL,2100-0600,2100-0600,OFF,OFF,2100-0600,SL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,OFF,OFF,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,OFF,NaN
4,3088783,103105143,thiminhthu.pham1@concentrix.com,PHAM THI MINH THU,20,1300-2200,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,OFF,0500-1400,0500-1400,0500-1400,OFF,0500-1400,0500-1400,OFF,0600-1500,0500-1400,0500-1400,0600-1500,0500-1400,OFF,0500-1400,0500-1400,0500-1400,0500-1400,0500-1400,OFF,OFF,NaN

In [299]:
# Loại bỏ hàng hiện đang dùng làm tên cột và đưa hàng đầu tiên của dữ liệu lên làm header mới

# Đặt hàng đầu tiên (hiện tại là dòng dữ liệu) làm tên cột mới
df_roster.columns = df_roster.iloc[0]

# Xóa hàng đầu tiên (vì đã dùng làm header)
df_roster = df_roster[1:].reset_index(drop=True)

print("Sau khi chỉnh lại header:")
print(df_roster.columns.tolist())
df_roster.head()

Sau khi chỉnh lại header:
['IEX', 'Emp ID', 'Email', 'Agent Name', 'Wave', '9/29/2025', '9/30/2025', '10/1/2025', '10/2/2025', '10/3/2025', '10/4/2025', '10/5/2025', '10/6/2025', '10/7/2025', '10/8/2025', '10/9/2025', '10/10/2025', '10/11/2025', '10/12/2025', '10/13/2025', '10/14/2025', '10/15/2025', '10/16/2025', '10/17/2025', '10/18/2025', '10/19/2025', '10/20/2025', '10/21/2025', '10/22/2025', '10/23/2025', '10/24/2025', '10/25/2025', '10/26/2025', nan]

,IEX,Emp ID,Email,Agent Name,Wave,9/29/2025,9/30/2025,10/1/2025,10/2/2025,10/3/2025,10/4/2025,10/5/2025,10/6/2025,10/7/2025,10/8/2025,10/9/2025,10/10/2025,10/11/2025,10/12/2025,10/13/2025,10/14/2025,10/15/2025,10/16/2025,10/17/2025,10/18/2025,10/19/2025,10/20/2025,10/21/2025,10/22/2025,10/23/2025,10/24/2025,10/25/2025,10/26/2025,NaN
0,3085257,103082161,thikimchi.le@concentrix.com,LE THI KIM CHI,17,2100-0600,2100-0600,OFF,OFF,2000-0500,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,NaN
1,3090069,103116487,thanhhao.nguyen@concentrix.com,NGUYEN THANH HAO,24,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,1300-2200,2100-0600,2100-0600,2100-0600,2100-0600,OFF,OFF,2100-0600,2100-0600,2100-0600,CO,AL,OFF,OFF,2100-0600,2000-0500,2000-0500,2000-0500,2000-0500,OFF,OFF,2000-0500,NaN
2,3087504,103101215,hongphuc.nguyen3@concentrix.com,NGUYEN HONG PHUC,20,1300-2200,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,OFF,2100-0600-SHAL,2100-0600-SHAL,AL,2100-0600,2100-0600,OFF,OFF,2100-0600,SL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,OFF,OFF,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,2100-0600-SHAL,OFF,NaN
3,3088783,103105143,thiminhthu.pham1@concentrix.com,PHAM THI MINH THU,20,1300-2200,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,OFF,0500-1400,0500-1400,0500-1400,OFF,0500-1400,0500-1400,OFF,0600-1500,0500-1400,0500-1400,0600-1500,0500-1400,OFF,0500-1400,0500-1400,0500-1400,0500-1400,0500-1400,OFF,OFF,NaN
4,3008097,102843519,songnguyen.nguyen@concentrix.com,NGUYEN SONG NGUYEN,26,2000-0500,AL,OFF,OFF,2000-0500,2000-0500,2000-0500,OFF,0600-1500,0600-1500,0600-1500,0600-1500,0600-1500,OFF,OFF,1300-2200,1300-2200,1300-2200,1300-2200,1300-2200,OFF,OFF,1300-2200,1300-2200,1300-2200,AL,AL,OFF,NaN

In [300]:
# Đọc sheet ATD_Final
atd_final_df = pd.read_excel(excel_path, sheet_name="ATD_Final")

# Đảm bảo cột Date trong atd_final_df có định dạng tháng/ngày/năm
atd_final_df['Date'] = pd.to_datetime(atd_final_df['Date'], errors='coerce').dt.strftime('%#m/%#d/%Y')


# Kiểm tra vài dòng đầu
atd_final_df.head()

,Year,Month,Site,Date Start Week,Day,Date,OracleID,IEX ID,Employee Name,Alias,LOB,TL ID,Supervisor Name,Manager/OM Name,Email Id,Wave,LWD/Movement,Detail Status,LOB_2,LOB_3,Active,Original.Shift,RTA.Start_Shift,RTA.End_Shift,Night_Shift,Shift Tracking,Roster Presented,Roster Scheduled,Target,Start Time,End Time,Duration,HC Actual,Time_Late,Time_Leave,Lateness,Open Time,OT,NCNS,SUM Productive,OT Ramco,NSA Group,OT Group,NM Group,Ramco Marked,HC Schedule,Leave.Shift,Leave.Leave_Datetime_Start_Shift,Leave.Leave_Datetime_End_Shift,Leave,Reason,Leave.Remark,Remark,Datetime_Start_Shift,Datetime_End_Shift,Shift,Attendance,Present,Planned,Unplanned,In Office,Re_Check,Ramco_ReCheck,Productive,Final_HC_Actual,HC_Schedule_Sum,Volume,Re-Direct,Exceed Chat
0,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102458550,3083115,TRAN THI THU HA,Nancy,Lodging,102211179,To Anh Duy,Patar Kirpan,thithuha.tran1@concentrix.com,4,NaT,Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN
1,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,103082161,3085257,LE THI KIM CHI,Sarah,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,thikimchi.le@concentrix.com,17,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN
2,2025,Oct-25,ONEHUB,2025-09-29,Thu,10/2/2025,103082161,3085257,LE THI KIM CHI,Sarah,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,thikimchi.le@concentrix.com,17,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,80,NaN,NaN,NaN
3,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102478278,3084782,VO THANH TIEN,Auty,Lodging,102371964,Tran Thao Uyen,Patar Kirpan,thanhtien.vo@concentrix.com,5,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN
4,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102821757,3004041,THAI HOANG PHU,Nine,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,hoangphu.thai@concentrix.com,9,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN

In [301]:

# Tính cột Actual Attendance
def compute_actual_attendance(row):
    schedule = str(row['Shift']).strip().upper()
    
    # Các trạng thái không tính attendance
    invalid_status = {"TERMINATION", "OFF CHAT", "", "0", "REMOVED"}
    if schedule in invalid_status:
        return ""
    
    # Trường hợp Mentor
    if schedule == "MENTOR":
        return "PR"
    
    # Các trường hợp còn lại giữ nguyên attendance gốc
    return row['Attendance']

atd_final_df['Actual Attendance'] = atd_final_df.apply(compute_actual_attendance, axis=1)

# Kiểm tra kết quả
atd_final_df.head()

,Year,Month,Site,Date Start Week,Day,Date,OracleID,IEX ID,Employee Name,Alias,LOB,TL ID,Supervisor Name,Manager/OM Name,Email Id,Wave,LWD/Movement,Detail Status,LOB_2,LOB_3,Active,Original.Shift,RTA.Start_Shift,RTA.End_Shift,Night_Shift,Shift Tracking,Roster Presented,Roster Scheduled,Target,Start Time,End Time,Duration,HC Actual,Time_Late,Time_Leave,Lateness,Open Time,OT,NCNS,SUM Productive,OT Ramco,NSA Group,OT Group,NM Group,Ramco Marked,HC Schedule,Leave.Shift,Leave.Leave_Datetime_Start_Shift,Leave.Leave_Datetime_End_Shift,Leave,Reason,Leave.Remark,Remark,Datetime_Start_Shift,Datetime_End_Shift,Shift,Attendance,Present,Planned,Unplanned,In Office,Re_Check,Ramco_ReCheck,Productive,Final_HC_Actual,HC_Schedule_Sum,Volume,Re-Direct,Exceed Chat,Actual Attendance
0,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102458550,3083115,TRAN THI THU HA,Nancy,Lodging,102211179,To Anh Duy,Patar Kirpan,thithuha.tran1@concentrix.com,4,NaT,Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN,WO
1,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,103082161,3085257,LE THI KIM CHI,Sarah,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,thikimchi.le@concentrix.com,17,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN,WO
2,2025,Oct-25,ONEHUB,2025-09-29,Thu,10/2/2025,103082161,3085257,LE THI KIM CHI,Sarah,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,thikimchi.le@concentrix.com,17,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,80,NaN,NaN,NaN,WO
3,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102478278,3084782,VO THANH TIEN,Auty,Lodging,102371964,Tran Thao Uyen,Patar Kirpan,thanhtien.vo@concentrix.com,5,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN,WO
4,2025,Oct-25,ONEHUB,2025-09-29,Wed,10/1/2025,102821757,3004041,THAI HOANG PHU,Nine,Lodging,102456914,Nguyen Dinh Nhu Hao,Patar Kirpan,hoangphu.thai@concentrix.com,9,NaT,Non Lodging Production,0,0,Yes,OFF,NaN,NaN,0,Off,0.0,0.0,0.0,NaT,NaT,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,WO,0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaT,NaT,OFF,WO,0.0,0.0,0.0,NaN,True,True,0.0,0.0,85,NaN,NaN,NaN,WO

In [302]:
# Đọc 3 file CSV
ramco_df = pd.read_csv("ramco_processed_oct_2025.csv")
active_df = pd.read_csv("Active.csv")
inactive_df = pd.read_csv("Inactive.csv")

# Hiển thị vài dòng đầu tiên của mỗi file
#ramco_df.head()
#active_df.head()
inactive_df.head()

,Site,Queue Group,CSG Joining Data,Location,People ID,IEX ID,OracleID,Employee Name,Alias,Gender,Contract Start Date,Contract End Date,Designation,Grade,LOB,Role,Multiple Chat Effective Date,Primary role,Secondary role,TL ID,Supervisor Name,Supervisor Email,Manager Name,Email Id,Wave,CCT Training,Lodging - Training start date,Lodging - Training end date,Lodging - Nesting Date,Lodging - Certification Date (Original),Lodging - Certification Date (Actual),Lodging - Certification status,Non-Lodging - Training start date,Non-Lodging - Training end date,Non-Lodging - Nesting Date,Non-Lodging - Certification Date,Non-Lodging - Certification Date (Actual),Non-Lodging - Certification status,Production Date,AON,Tenure,Current Queue Production Date,Current Queue Production Duration,Current Queue Tenure,Nationality,MSA,Current Console Queue,LWD/Movement,Attrition Type,Reason for Attrition,Month,Week Ending,Termination Date,Duration,WS,Note,Okta Deletion,Check if still stay in Active sheet
0,QTSC,-,-,Vietnam,NaN,NaN,102356310,LE THANH PHONG,NaN,Male,2023-10-25 00:00:00,2024-10-24 00:00:00,"Supervisor, Training & Quality",Grade 9A,Support,NaN,NaN,-,-,102321297,JoRoy Alcazar,jonathanroy.alcazar@concentrix.com,Gaurav Thakkar,lethanhphong.tran@concentrix.com,APAC 3,2023-11-06 00:00:00,2023-11-06 00:00:00,2023-12-29 00:00:00,2024-01-02 00:00:00,2024-01-12 00:00:00,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,Vietnamese,Expedia,-,2023-11-10 00:00:00,Voluntary,Terminate Employee > Voluntary > Personal,Nov'23,2023-11-12 00:00:00,2023-11-10 00:00:00,In Training,2023-11-06 00:00:00,NaN,Y,No
1,QTSC,-,-,Vietnam,NaN,NaN,102369332,LE BAO NGOC AN,NaN,Female,2023-11-15 00:00:00,2024-11-14 00:00:00,"Supervisor, Training & Quality",Grade 9A,Support,NaN,NaN,-,-,102321297,JoRoy Alcazar,jonathanroy.alcazar@concentrix.com,Gaurav Thakkar,baongocan.le@concentrix.com,APAC 3,2023-11-06 00:00:00,2023-11-06 00:00:00,2023-12-29 00:00:00,2024-01-02 00:00:00,2024-01-12 00:00:00,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,Vietnamese,Expedia,-,2023-11-21 00:00:00,Voluntary,Terminate Employee > Voluntary > Personal,Nov'23,2023-11-26 00:00:00,2023-11-21 00:00:00,In Training,2023-11-20 00:00:00,NaN,Y,No
2,QTSC,-,-,Vietnam,NaN,NaN,102361154,HUYNH QUANG TIEN,NaN,Male,2023-11-02 00:00:00,2024-11-01 00:00:00,"Team Leader, Operations",Grade 9A,Support,NaN,NaN,-,-,102240407,Han My Linh,mylinh.han@concentrix.com,Rojo Sir William,quangtien.huynh@concentrix.com,APAC 3,2023-11-06 00:00:00,2023-11-06 00:00:00,2023-12-29 00:00:00,2024-01-02 00:00:00,2024-01-12 00:00:00,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,Vietnamese,Expedia,-,2023-11-26 00:00:00,Involuntary,Terminate Employee > Involuntary > Failed to M...,Nov'23,2023-11-26 00:00:00,2023-11-26 00:00:00,In Training,2023-11-20 00:00:00,NaN,Y,No
3,QTSC,-,-,Vietnam,NaN,NaN,102370708,TRAN NGOC KHANH DUYEN,NaN,Female,2023-11-20 00:00:00,2024-01-18 00:00:00,"Advisor I, Customer Service",Grade 12,Lodging,Single_Chat,NaN,Chat,-,102264985,Tran Viet Hung,viethung.tran@concentrix.com,Pradeep Kumar Bahadursha,ngockhanhduyen.tran@concentrix.com,1B,2023-11-20 00:00:00,2023-11-20 00:00:00,2023-12-15 00:00:00,2023-12-18 00:00:00,2023-12-29 00:00:00,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,Vietnamese,Expedia,Chat_OD_EN_Lodging,2023-12-01 00:00:00,Involuntary,Terminate Employee > Involuntary > Attendance ...,Dec'23,2023-12-03 00:00:00,2023-12-01 00:00:00,In Training,2023-11-27 00:00:00,NaN,Y,No
4,-,-,-,Vietnam,NaN,NaN,102464530,PHAM MINH THU,NaN,Female,-,-,"Advisor I, Customer Service",Grade 12,-,NaN,NaN,-,-,-,-,-,-,NaN,3B,2024-01-02 00:00:00,2024-01-02 00:00:00,2024-01-26 00:00:00,2024-01-29 00:00:00,2024-02-11 00:00:00,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,Vietnamese,Expedia,-,2024-01-02 00:00:00,NaN,DNS,Jan'24,2024-01-07 00:00:00,-,CCT Training,,Dropped in Training,Y,No

In [303]:
# Merge với active_df trước
active_merge = atd_final_df[['OracleID', 'Date', 'Employee Name', 'Actual Attendance']].merge(
    active_df[['OracleID', 'LOB', 'Supervisor Name', 'Manager/OM Name']],
    on='OracleID',
    how='left'
)

# Merge với inactive_df (và đổi tên cột Manager Name)
inactive_merge = atd_final_df[['OracleID', 'Date', 'Employee Name', 'Actual Attendance']].merge(
    inactive_df[['OracleID', 'LOB', 'Supervisor Name', 'Manager Name']].rename(
        columns={'Manager Name': 'Manager/OM Name'}
    ),
    on='OracleID',
    how='left'
)

# Dùng combine_first để lấy giá trị từ inactive nếu active bị thiếu
report_base_df = active_merge.combine_first(inactive_merge)

# Hiển thị kết quả mẫu
report_base_df.head()

,OracleID,Date,Employee Name,Actual Attendance,LOB,Supervisor Name,Manager/OM Name
0,102458550,10/1/2025,TRAN THI THU HA,WO,Lodging,To Anh Duy,Patar Kirpan
1,103082161,10/1/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan
2,103082161,10/2/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan
3,102478278,10/1/2025,VO THANH TIEN,WO,Lodging,Tran Thao Uyen,Patar Kirpan
4,102821757,10/1/2025,THAI HOANG PHU,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan

In [304]:
# Unpivot (melt) các cột ngày trong ramco_df
# Giả sử các cột không phải ngày là các cột định danh (ID, Name, v.v.)

id_vars = ['Oracle_ID', 'Employee Name']  # thay đổi nếu bạn có thêm các cột định danh khác
value_vars = [col for col in ramco_df.columns if col not in id_vars]

ramco_unpivot_df = ramco_df.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Date',
    value_name='Ramco Attendance'
)

# Chuẩn hóa lại cột Date nếu cần (nếu cột đang là dạng chuỗi YYYY-MM-DD)
ramco_unpivot_df['Date'] = pd.to_datetime(ramco_unpivot_df['Date'], errors='coerce').dt.strftime('%#m/%#d/%Y')

# Xem vài dòng đầu
ramco_unpivot_df

        Oracle_ID               Employee Name        Date Ramco Attendance
0            2212                Nadia  Durri   10/1/2025               NM
1            2892                 Matt  Bagby   10/1/2025               NM
2           10067                   Kenny  Ng   10/1/2025               NM
3           10658        Jayavelu  Maripillai   10/1/2025               NM
4           14211                  Pammy  Leo   10/1/2025               NM
...           ...                         ...         ...              ...
662837     884365              NORLEZA  SEMAN  10/31/2025               NM
662838     885486  PAVITHIRAN  SHUNMUGANATHAN  10/31/2025               NM
662839     886398    NESSIE DAWN OBSID  TANZO  10/31/2025               NM
662840     887374              REVATHI  MOGAN  10/31/2025               NM
662841     892259              SANDEEP  KUMAR  10/31/2025               NM

[662842 rows x 4 columns]

In [305]:
# Đảm bảo tên cột khớp trước khi merge
ramco_unpivot_df = ramco_unpivot_df.rename(columns={'Oracle_ID': 'OracleID'})

# Gộp dữ liệu từ ramco_unpivot_df vào report_base_df theo OracleID + Date
report_base_df = report_base_df.merge(
    ramco_unpivot_df[['OracleID', 'Date', 'Ramco Attendance']],
    on=['OracleID', 'Date'],
    how='left'
)

# Kiểm tra kết quả sau khi thêm cột Ramco Attendance
report_base_df

,OracleID,Date,Employee Name,Actual Attendance,LOB,Supervisor Name,Manager/OM Name,Ramco Attendance
0,102458550,10/1/2025,TRAN THI THU HA,WO,Lodging,To Anh Duy,Patar Kirpan,WO
1,103082161,10/1/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO
2,103082161,10/2/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO
3,102478278,10/1/2025,VO THANH TIEN,WO,Lodging,Tran Thao Uyen,Patar Kirpan,WO
4,102821757,10/1/2025,THAI HOANG PHU,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO
...,...,...,...,...,...,...,...,...
3549,102871040,10/14/2025,TRAN PHAM MINH THU,HAL,Lodging,Ann,Patar Kirpan,HAL
3550,103283831,10/18/2025,TRAN TUAN KHOI,HAL,Lodging,Truong Thien Thanh Toan,Patar Kirpan,HAL
3551,103109357,10/18/2025,VUU TIEN NHAN,HAL,Lodging,To Anh Duy,Patar Kirpan,HAL
3552,103085298,10/18/2025,DOAN AN NY,HAL,Lodging,To Anh Duy,Patar Kirpan,HAL
3553,102864715,10/22/2025,NGO VAN MINH DUY,HAL,Lodging,Mia Minh Lê,Patar Kirpan,PR

In [306]:
# Đặt khoảng ngày cần hiển thị
start_date = "10/1/2025"
end_date = "10/15/2025"

# Chuyển cột Date về dạng datetime để lọc
report_base_df['Date_dt'] = pd.to_datetime(report_base_df['Date'], errors='coerce')
start_dt = pd.to_datetime(start_date)
end_dt = pd.to_datetime(end_date)

# Lọc dữ liệu theo khoảng ngày mong muốn
filtered_report_df = report_base_df[
    (report_base_df['Date_dt'] >= start_dt) & (report_base_df['Date_dt'] <= end_dt)
]

#Những agent đã bị ter sẽ bị hiện giá trị LOB, Supervisor Name là NaN, vì thế cần map những dòng mà có LOB, hoặc Supervisor Name là NaN thì
#sẽ map nó với bảng inactive

# Hiển thị kết quả
filtered_report_df

,OracleID,Date,Employee Name,Actual Attendance,LOB,Supervisor Name,Manager/OM Name,Ramco Attendance,Date_dt
0,102458550,10/1/2025,TRAN THI THU HA,WO,Lodging,To Anh Duy,Patar Kirpan,WO,2025-10-01
1,103082161,10/1/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO,2025-10-01
2,103082161,10/2/2025,LE THI KIM CHI,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO,2025-10-02
3,102478278,10/1/2025,VO THANH TIEN,WO,Lodging,Tran Thao Uyen,Patar Kirpan,WO,2025-10-01
4,102821757,10/1/2025,THAI HOANG PHU,WO,Lodging,Nguyen Dinh Nhu Hao,Patar Kirpan,WO,2025-10-01
...,...,...,...,...,...,...,...,...,...
3545,103109090,10/8/2025,VI LE HOAI ANH,HAL,Lodging,To Anh Duy,Patar Kirpan,HAL,2025-10-08
3546,102477510,10/11/2025,HUYNH NGOC HUE TRANG,HAL,Lodging,Tran Sharon,Patar Kirpan,HAL,2025-10-11
3547,103085298,10/12/2025,DOAN AN NY,HAL,Lodging,To Anh Duy,Patar Kirpan,HAL,2025-10-12
3548,103109091,10/12/2025,NGUYEN NGOC SON,HAL,Lodging,To Anh Duy,Patar Kirpan,HAL,2025-10-12
3549,102871040,10/14/2025,TRAN PHAM MINH THU,HAL,Lodging,Ann,Patar Kirpan,HAL,2025-10-14