In [129]:
import pandas as pd
from datetime import datetime

# Hiển thị đủ số dòng và số cột mong muốn
pd.set_option("display.max_rows", 100)   # tối đa số dòng hiển thị
pd.set_option("display.max_columns", None)  # hiện tất cả các cột
pd.set_option("display.width", None)   # không giới hạn độ rộng

In [130]:
# Đường dẫn file CSV
csv_path = "RAMCO-OCT-2025.csv"

In [131]:
# Đọc file
df = pd.read_csv(csv_path)
print("Kích thước ban đầu:", df.shape)
df.head()

Kích thước ban đầu: (21383, 36)

,#,OU,employee_code,employee_name,Employee Type,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
0,1,NaN,NaN,NaN,NaN,01-Oct-2025,02-Oct-2025,03-Oct-2025,04-Oct-2025,05-Oct-2025,06-Oct-2025,07-Oct-2025,08-Oct-2025,09-Oct-2025,10-Oct-2025,11-Oct-2025,12-Oct-2025,13-Oct-2025,14-Oct-2025,15-Oct-2025,16-Oct-2025,17-Oct-2025,18-Oct-2025,19-Oct-2025,20-Oct-2025,21-Oct-2025,22-Oct-2025,23-Oct-2025,24-Oct-2025,25-Oct-2025,26-Oct-2025,27-Oct-2025,28-Oct-2025,29-Oct-2025,30-Oct-2025,31-Oct-2025
1,2,Concentrix CVG Malaysia Sdn. Bhd.,2212.0,Nadia Durri,Consultant,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,3,Concentrix Malaysia Sdn. Bhd,2892.0,Matt Bagby,Consultant,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,4,Concentrix CVG Malaysia Sdn. Bhd.,10067.0,Kenny Ng,Consultant,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,5,Concentrix Malaysia Sdn. Bhd,10658.0,Jayavelu Maripillai,Consultant,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [132]:
# Xóa các cột không cần thiết
cols_to_remove = ["#", "OU", "Employee Type"]
df = df.drop(columns=[col for col in cols_to_remove if col in df.columns])
print("Sau khi xóa cột:", df.shape)
df.head()

Sau khi xóa cột: (21383, 33)

,employee_code,employee_name,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
0,NaN,NaN,01-Oct-2025,02-Oct-2025,03-Oct-2025,04-Oct-2025,05-Oct-2025,06-Oct-2025,07-Oct-2025,08-Oct-2025,09-Oct-2025,10-Oct-2025,11-Oct-2025,12-Oct-2025,13-Oct-2025,14-Oct-2025,15-Oct-2025,16-Oct-2025,17-Oct-2025,18-Oct-2025,19-Oct-2025,20-Oct-2025,21-Oct-2025,22-Oct-2025,23-Oct-2025,24-Oct-2025,25-Oct-2025,26-Oct-2025,27-Oct-2025,28-Oct-2025,29-Oct-2025,30-Oct-2025,31-Oct-2025
1,2212.0,Nadia Durri,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,2892.0,Matt Bagby,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,10067.0,Kenny Ng,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,10658.0,Jayavelu Maripillai,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [133]:
# Xóa hàng đầu tiên và đưa hàng chứa ngày lên làm tên cột
df.columns = df.iloc[0]   # gán hàng đầu tiên làm tên cột
df = df[1:].reset_index(drop=True)  # xóa hàng đầu tiên, reset lại index
print("Sau khi chỉnh lại header:", df.shape)
df.head()

Sau khi chỉnh lại header: (21382, 33)

,NaN,NaN,01-Oct-2025,02-Oct-2025,03-Oct-2025,04-Oct-2025,05-Oct-2025,06-Oct-2025,07-Oct-2025,08-Oct-2025,09-Oct-2025,10-Oct-2025,11-Oct-2025,12-Oct-2025,13-Oct-2025,14-Oct-2025,15-Oct-2025,16-Oct-2025,17-Oct-2025,18-Oct-2025,19-Oct-2025,20-Oct-2025,21-Oct-2025,22-Oct-2025,23-Oct-2025,24-Oct-2025,25-Oct-2025,26-Oct-2025,27-Oct-2025,28-Oct-2025,29-Oct-2025,30-Oct-2025,31-Oct-2025
0,2212.0,Nadia Durri,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
1,2892.0,Matt Bagby,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,10067.0,Kenny Ng,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,10658.0,Jayavelu Maripillai,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,14211.0,Pammy Leo,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [134]:
# Đổi tên và định dạng lại cột đầu tiên
# Giả định cột đầu tiên hiện không có tên rõ ràng (ví dụ NaN hoặc trống)
df = df.rename(columns={df.columns[0]: "Oracle_ID", df.columns[1]: "Employee Name"})
df.head()

,Oracle_ID,Employee Name,01-Oct-2025,02-Oct-2025,03-Oct-2025,04-Oct-2025,05-Oct-2025,06-Oct-2025,07-Oct-2025,08-Oct-2025,09-Oct-2025,10-Oct-2025,11-Oct-2025,12-Oct-2025,13-Oct-2025,14-Oct-2025,15-Oct-2025,16-Oct-2025,17-Oct-2025,18-Oct-2025,19-Oct-2025,20-Oct-2025,21-Oct-2025,22-Oct-2025,23-Oct-2025,24-Oct-2025,25-Oct-2025,26-Oct-2025,27-Oct-2025,28-Oct-2025,29-Oct-2025,30-Oct-2025,31-Oct-2025
0,2212.0,Nadia Durri,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
1,2892.0,Matt Bagby,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,10067.0,Kenny Ng,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,10658.0,Jayavelu Maripillai,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,14211.0,Pammy Leo,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [135]:
# Chuyển Oracle_ID về dạng string (để không bị float hoặc mất số 0 đầu)
df["Oracle_ID"] = df["Oracle_ID"].astype(str).str.strip().str.replace(r"\.0$", "", regex=True)

df.head()

,Oracle_ID,Employee Name,01-Oct-2025,02-Oct-2025,03-Oct-2025,04-Oct-2025,05-Oct-2025,06-Oct-2025,07-Oct-2025,08-Oct-2025,09-Oct-2025,10-Oct-2025,11-Oct-2025,12-Oct-2025,13-Oct-2025,14-Oct-2025,15-Oct-2025,16-Oct-2025,17-Oct-2025,18-Oct-2025,19-Oct-2025,20-Oct-2025,21-Oct-2025,22-Oct-2025,23-Oct-2025,24-Oct-2025,25-Oct-2025,26-Oct-2025,27-Oct-2025,28-Oct-2025,29-Oct-2025,30-Oct-2025,31-Oct-2025
0,2212,Nadia Durri,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
1,2892,Matt Bagby,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,10067,Kenny Ng,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,10658,Jayavelu Maripillai,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,14211,Pammy Leo,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [136]:
from dateutil import parser
import re

def normalize_col_name_to_mdY(col):
    # Nếu đã là datetime-like (pandas Timestamp)
    try:
        if hasattr(col, "year") and hasattr(col, "month") and hasattr(col, "day"):
            return f"{col.month}/{col.day}/{col.year}"
    except Exception:
        pass

    s = str(col).strip()

    # Thay mọi loại dash/non-breaking hyphen thành dấu '-' chuẩn
    s = re.sub(r"[\u2010\u2011\u2012\u2013\u2014\u2212]", "-", s)

    # Loại bỏ ký tự không in được (zero-width, nbsp, ...)
    s = re.sub(r"[\u00A0\u200B\u200C\u200D\uFEFF]", "", s)

    # Nếu đã là dạng số miễn là không chứa chữ, giữ nguyên (ví dụ 'Oracle_ID' hoặc '123')
    if re.search(r"[A-Za-z]", s) is None and re.search(r"\d", s) is not None:
        return s

    # Thử parse bằng định dạng cố định dd-MMM-YYYY (ví dụ 01-Oct-2025)
    for fmt in ("%d-%b-%Y", "%d-%b-%y", "%d/%b/%Y", "%d/%b/%y", "%d-%B-%Y", "%d %b %Y"):
        try:
            dt = pd.to_datetime(s, format=fmt, errors="raise")
            return f"{dt.month}/{dt.day}/{dt.year}"
        except Exception:
            pass

    # Thử pd.to_datetime với dayfirst (gợi ý: dd-MMM-YYYY)
    try:
        dt = pd.to_datetime(s, dayfirst=True, errors="coerce")
        if not pd.isna(dt):
            return f"{dt.month}/{dt.day}/{dt.year}"
    except Exception:
        pass

    # Cuối cùng thử dateutil.parser (linh hoạt hơn)
    try:
        dt = parser.parse(s, dayfirst=True, fuzzy=True)
        return f"{dt.month}/{dt.day}/{dt.year}"
    except Exception:
        pass

    # Nếu tất cả thất bại, trả về tên nguyên gốc (sau strip)
    return s

# Áp dụng cho tất cả tên cột
new_columns = [normalize_col_name_to_mdY(c) for c in df.columns]
df.columns = new_columns

print("Tên cột sau khi chuẩn hóa:")
print(df.columns.tolist())
df.tail()

Tên cột sau khi chuẩn hóa:
['Oracle_ID', 'Employee Name', '10/1/2025', '10/2/2025', '10/3/2025', '10/4/2025', '10/5/2025', '10/6/2025', '10/7/2025', '10/8/2025', '10/9/2025', '10/10/2025', '10/11/2025', '10/12/2025', '10/13/2025', '10/14/2025', '10/15/2025', '10/16/2025', '10/17/2025', '10/18/2025', '10/19/2025', '10/20/2025', '10/21/2025', '10/22/2025', '10/23/2025', '10/24/2025', '10/25/2025', '10/26/2025', '10/27/2025', '10/28/2025', '10/29/2025', '10/30/2025', '10/31/2025']

,Oracle_ID,Employee Name,10/1/2025,10/2/2025,10/3/2025,10/4/2025,10/5/2025,10/6/2025,10/7/2025,10/8/2025,10/9/2025,10/10/2025,10/11/2025,10/12/2025,10/13/2025,10/14/2025,10/15/2025,10/16/2025,10/17/2025,10/18/2025,10/19/2025,10/20/2025,10/21/2025,10/22/2025,10/23/2025,10/24/2025,10/25/2025,10/26/2025,10/27/2025,10/28/2025,10/29/2025,10/30/2025,10/31/2025
21377,884365,NORLEZA SEMAN,PR,PR,PR,WO,WO,PR,PR,PR,PR,PR,WO,WO,PR,PR,PR,PR,PR,WO,WO,PH,PR,PR,PR,NM,NM,NM,NM,NM,NM,NM,NM
21378,885486,PAVITHIRAN SHUNMUGANATHAN,WO,WO,PR,SL,PR,PR,PR,WO,PR,PR,PR,WO,PR,PR,PR,PR,PR,WO,WO,HO,CO,CO,AL,AL,NM,NM,AL,NM,NM,NM,NM
21379,886398,NESSIE DAWN OBSID TANZO,PR,PR,WO,WO,PR,PR,PR,PR,PR,WO,WO,PR,PR,PR,PR,PR,NM,WO,WO,PH,PR,PR,NM,NM,WO,WO,NM,NM,NM,NM,NM
21380,887374,REVATHI MOGAN,PR,PR,PR,WO,WO,PR,PR,PR,PR,PR,WO,WO,PR,PR,PR,PR,PR,WO,WO,HO,AL,AL,AL,AL,NM,NM,NM,NM,NM,NM,NM
21381,892259,SANDEEP KUMAR,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [137]:
import os

# 1. Kiểm tra index có cần giữ không
if df.index.equals(pd.RangeIndex(start=0, stop=len(df), step=1)):
    print("Index chỉ là mặc định, sẽ được loại bỏ.")
    df = df.reset_index(drop=True)
else:
    print("Index chứa thông tin, sẽ được giữ lại.")

df.head()

Index chỉ là mặc định, sẽ được loại bỏ.

,Oracle_ID,Employee Name,10/1/2025,10/2/2025,10/3/2025,10/4/2025,10/5/2025,10/6/2025,10/7/2025,10/8/2025,10/9/2025,10/10/2025,10/11/2025,10/12/2025,10/13/2025,10/14/2025,10/15/2025,10/16/2025,10/17/2025,10/18/2025,10/19/2025,10/20/2025,10/21/2025,10/22/2025,10/23/2025,10/24/2025,10/25/2025,10/26/2025,10/27/2025,10/28/2025,10/29/2025,10/30/2025,10/31/2025
0,2212,Nadia Durri,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
1,2892,Matt Bagby,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
2,10067,Kenny Ng,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
3,10658,Jayavelu Maripillai,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM
4,14211,Pammy Leo,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,HO,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM

In [138]:
# 2. Đặt tên file xuất
csv_path = "ramco_processed_oct_2025.csv"
xlsx_path = "ramco_processed_oct_2025.xlsx"

# 3. Ghi file, ghi đè nếu tồn tại
df.to_csv(csv_path, index=False) #file này là để đọc trong notebook khác
df.to_excel(xlsx_path, index=False) #file này là để gửi cho bên Ops hoặc TQA hoặc đồng nghiệp

print(f"Đã ghi đè file:\n - {os.path.abspath(csv_path)}\n - {os.path.abspath(xlsx_path)}")

Đã ghi đè file:
 - c:\Users\huuchinh.nguyen\Concentrix Corporation\WFM-Expedia-HCM - Branding files\Vu\mismatch-ramco\ramco_processed_oct_2025.csv
 - c:\Users\huuchinh.nguyen\Concentrix Corporation\WFM-Expedia-HCM - Branding files\Vu\mismatch-ramco\ramco_processed_oct_2025.xlsx